export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
export const LIST_TODO = "LIST_TODO";

export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST";
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS";
export const TODO_LIST_FAIL = "TODO_LIST_FAIL";


export const TODO_SAVE_REQUEST = "TODO_SAVE_REQUEST";
export const TODO_SAVE_SUCCESS = "TODO_SAVE_SUCCESS";
export const TODO_SAVE_FAIL = "TODO_SAVE_FAIL";

export const TODO_TOGGLE_REQUEST = "TODO_TOGGLE_REQUEST";
export const TODO_TOGGLE_SUCCESS = "TODO_TOGGLE_SUCCESS";
export const TODO_TOGGLE_FAIL = "TODO_TOGGLE_FAIL";


export const REODER_ITEMS = "REODER_ITEMS"